-- EXPLOROTORY OF DATA

SELECT *
FROM layoffs_3;

-- LOOKING AT WHICH COMPANY LAID OFF MOST TO LEAST EMPLOYEE 

SELECT COMPANY , SUM(total_laid_off)
FROM layoffs_3
GROUP BY COMPANY
ORDER BY SUM(total_laid_off) DESC;

-- PERCENTAGE OF LAID OFF 

SELECT COMPANY , SUM(percentage_laid_off)
FROM layoffs_3
GROUP BY COMPANY
ORDER BY 2 DESC ;

-- which country laid off most to least

SELECT country , sum(total_laid_off)
FROM layoffs_3
GROUP BY COUNTRY
ORDER BY sum(total_laid_off) DESC;

-- IN WHICH YEAR UNITED STATES LAID OFF MOST 

SELECT SUBSTRING(`DATE`,1,4) AS `YEARS`, SUM(TOTAL_LAID_OFF)
FROM layoffs_3
WHERE COUNTRY = 'UNITED STATES'
GROUP BY `YEARS`
ORDER BY 1;

-- MOST FUND RAISED BY COUNTRY 

SELECT COUNTRY , SUM(FUNDS_RAISED_MILLIONS) AS MOST_FUND_RAISED
FROM layoffs_3
GROUP BY COUNTRY
ORDER BY MOST_FUND_RAISED DESC;

--  HOW MANY LAID OFF IS DONE BY MONTHS 

SELECT substring(`DATE`,1,7) AS `MONTHS`, SUM(TOTAL_LAID_OFF)
FROM layoffs_3
GROUP BY `MONTHS`
ORDER BY 1;


-- COMPANIES WHICH LAID OFF 100%

SELECT COMPANY , SUM(percentage_laid_off) AS SUM_PER
FROM layoffs_3
GROUP BY COMPANY
HAVING SUM_PER = 1;

-- OR

SELECT COMPANY FROM layoffs_3 WHERE percentage_laid_off =1;


-- industry which laid off most IN WHICH YEAR

WITH CTE (COMPANY , YEARS , SUM_TOTAL)AS
(
SELECT COMPANY,  YEAR(`DATE`)	, SUM(TOTAL_LAID_OFF) 
FROM layoffs_3
GROUP BY COMPANY , YEAR(`DATE`)
),
CTE2 AS
(
SELECT * , 
DENSE_RANK() OVER(PARTITION BY YEARS ORDER BY SUM_TOTAL DESC) AS RANKING
FROM CTE
WHERE YEARS IS NOT NULL
)
SELECT * 
FROM CTE2
WHERE RANKING<6;